const express = require('express')
const router = express.Router()
const passport = require('passport')
const adminController = require('../../controllers/adminController')
const { isAdmin, checkLogin } = require('../../middleware/auth')
// router.use(checkLogin, isAdmin)
router.get('/orders', adminController.renderOrders)
router.get('/orders/:id', adminController.editOrderPage)
router.post('/orders/:id/check',adminController.checkOrderChange)
router.put('/orders/:id',adminController.putOrder)
module.exports = router
