const express = require('express')
const router = express.Router()
const user = require('./modules/user')
const auth = require('./modules/auth')
const home = require('./modules/home')
const product = require('./modules/product')
const wishlist = require('./modules/wishlist')
const cart = require('./modules/cart')
const order = require('./modules/order')
const admin = require('./modules/admin')

router.use('/admin',admin)
router.use('/auth', auth)
router.use('/users', user)
router.use('/wishlist', wishlist)
router.use('/orders', order)
router.use('/cart', cart)
router.use('/products', product)
router.use('/', home)

module.exports = router
